# Generated by Django 3.2.12 on 2024-03-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
    ]
